(* Driver for the extracted LJF proof-search procedure.

   Build and run (from this directory):
     dune exec ./driver.exe

   ljfps_search.ml / .mli are generated by Rocq extraction. After changing
   anything under src/, regenerate them from the repository root with:
     make -j4          (-j4 = up to 4 parallel jobs; affects speed only)

   try_decide_sequent returns:
     Some true   derivable      - carries a machine-checked derivation
     Some false  not derivable  - carries a machine-checked refutation
     None        inconclusive   - no branch yielded a proof, and every branch
                                  was either refuted or inconclusive, with at
                                  least one inconclusive (the search revisited
                                  a focus decision). A refutation needs *all*
                                  alternatives refuted, so none could be
                                  assembled. By Underivable_iff_Search_Returns_Some_Right_or_None
                                  this still means not derivable, but no
                                  witness is produced.
*)

open Ljfps_search

let empty_ctx : pndctx = []

let a = Atom (Pos, 0)
let b = Atom (Pos, 1)
let c = Atom (Pos, 2)

let seq = Sbct (empty_ctx, [a; Imp (a, b)], c)

let show name seq =
  match try_decide_sequent seq with
  | Some true  -> Printf.printf "%s: Derivable\n" name
  | Some false -> Printf.printf "%s: Not derivable - with a witness\n" name
  | None       -> Printf.printf "%s: Not derivable - without a witness\n" name

let () =
  show "seq" seq;
